#!/usr/bin/env bash

tags() {
  while sleep 1; do
    echo "$(river-bedload -print active | jq '[.[] | select(.occupied == true) | .id]')"
  done
}
focused() {
  while sleep 1; do
    river-bedload -print focused | jq -r '.[].focused_id'
  done
}

case "$1" in
"tag")
  tags
  ;;
"focused")
  focused
  ;;
*)
  echo "[]"
  ;;
esac
