#!/bin/bash
WALLPAPER_DIR="$HOME/.config/Wallpaper" # Change this to your wallpapers directory

# List PNG/JPG files (case-insensitive)
find "$WALLPAPER_DIR" -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" \) | sort
